package com.data.mapper;

import com.data.pojo.VoteSubjectoption;
import com.data.pojo.VoteSubjectoptionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteSubjectoptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    long countByExample(VoteSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int deleteByExample(VoteSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int insert(VoteSubjectoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int insertSelective(VoteSubjectoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    List<VoteSubjectoption> selectByExampleWithRowbounds(VoteSubjectoptionCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    List<VoteSubjectoption> selectByExample(VoteSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    VoteSubjectoption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteSubjectoption record, @Param("example") VoteSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteSubjectoption record, @Param("example") VoteSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteSubjectoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteSubjectoption record);
}