package com.data.mapper;

import com.data.pojo.VotePkSubjectoption;
import com.data.pojo.VotePkSubjectoptionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VotePkSubjectoptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    long countByExample(VotePkSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int deleteByExample(VotePkSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int insert(VotePkSubjectoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int insertSelective(VotePkSubjectoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    List<VotePkSubjectoption> selectByExampleWithRowbounds(VotePkSubjectoptionCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    List<VotePkSubjectoption> selectByExample(VotePkSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    VotePkSubjectoption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VotePkSubjectoption record, @Param("example") VotePkSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VotePkSubjectoption record, @Param("example") VotePkSubjectoptionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VotePkSubjectoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VotePkSubjectoption record);
}