package com.data.mapper;

import com.data.pojo.VoteSubject;
import com.data.pojo.VoteSubjectCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    long countByExample(VoteSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int deleteByExample(VoteSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int insert(VoteSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int insertSelective(VoteSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    List<VoteSubject> selectByExampleWithRowbounds(VoteSubjectCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    List<VoteSubject> selectByExample(VoteSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    VoteSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteSubject record, @Param("example") VoteSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteSubject record, @Param("example") VoteSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteSubject record);
}