package com.data.mapper;

import com.data.pojo.VotePkSubject;
import com.data.pojo.VotePkSubjectCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VotePkSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    long countByExample(VotePkSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int deleteByExample(VotePkSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int insert(VotePkSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int insertSelective(VotePkSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    List<VotePkSubject> selectByExampleWithRowbounds(VotePkSubjectCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    List<VotePkSubject> selectByExample(VotePkSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    VotePkSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VotePkSubject record, @Param("example") VotePkSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VotePkSubject record, @Param("example") VotePkSubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VotePkSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VotePkSubject record);
}