package com.data.mapper;

import com.data.pojo.VoteSubjectanswer;
import com.data.pojo.VoteSubjectanswerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteSubjectanswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    long countByExample(VoteSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int deleteByExample(VoteSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int insert(VoteSubjectanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int insertSelective(VoteSubjectanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    List<VoteSubjectanswer> selectByExampleWithRowbounds(VoteSubjectanswerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    List<VoteSubjectanswer> selectByExample(VoteSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    VoteSubjectanswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteSubjectanswer record, @Param("example") VoteSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteSubjectanswer record, @Param("example") VoteSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteSubjectanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteSubjectanswer record);
}