package com.data.mapper;

import com.data.pojo.VotePkSubjectanswer;
import com.data.pojo.VotePkSubjectanswerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VotePkSubjectanswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    long countByExample(VotePkSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int deleteByExample(VotePkSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int insert(VotePkSubjectanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int insertSelective(VotePkSubjectanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    List<VotePkSubjectanswer> selectByExampleWithRowbounds(VotePkSubjectanswerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    List<VotePkSubjectanswer> selectByExample(VotePkSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    VotePkSubjectanswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VotePkSubjectanswer record, @Param("example") VotePkSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VotePkSubjectanswer record, @Param("example") VotePkSubjectanswerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VotePkSubjectanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectanswer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VotePkSubjectanswer record);
}