package com.data.pojo;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.motto
     *
     * @mbg.generated
     */
    private String motto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.schooling
     *
     * @mbg.generated
     */
    private String schooling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.profession
     *
     * @mbg.generated
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.income
     *
     * @mbg.generated
     */
    private String income;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.teacherId
     *
     * @mbg.generated
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.teacheName
     *
     * @mbg.generated
     */
    private String teachename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.people
     *
     * @mbg.generated
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ident
     *
     * @mbg.generated
     */
    private String ident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.rhdate
     *
     * @mbg.generated
     */
    private Date rhdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ssqs
     *
     * @mbg.generated
     */
    private String ssqs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.csdd
     *
     * @mbg.generated
     */
    private String csdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.userType
     *
     * @mbg.generated
     */
    private String usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.praise
     *
     * @mbg.generated
     */
    private Integer praise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.follow
     *
     * @mbg.generated
     */
    private Integer follow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.publish
     *
     * @mbg.generated
     */
    private Integer publish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.wealth
     *
     * @mbg.generated
     */
    private Double wealth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.balance
     *
     * @mbg.generated
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.introduce
     *
     * @mbg.generated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.userId
     *
     * @return the value of account.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.userId
     *
     * @param userid the value for account.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone
     *
     * @return the value of account.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone
     *
     * @param phone the value for account.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.nickName
     *
     * @return the value of account.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.nickName
     *
     * @param nickname the value for account.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.userName
     *
     * @return the value of account.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.userName
     *
     * @param username the value for account.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.motto
     *
     * @return the value of account.motto
     *
     * @mbg.generated
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.motto
     *
     * @param motto the value for account.motto
     *
     * @mbg.generated
     */
    public void setMotto(String motto) {
        this.motto = motto == null ? null : motto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.birthday
     *
     * @return the value of account.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.birthday
     *
     * @param birthday the value for account.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.schooling
     *
     * @return the value of account.schooling
     *
     * @mbg.generated
     */
    public String getSchooling() {
        return schooling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.schooling
     *
     * @param schooling the value for account.schooling
     *
     * @mbg.generated
     */
    public void setSchooling(String schooling) {
        this.schooling = schooling == null ? null : schooling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sex
     *
     * @return the value of account.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sex
     *
     * @param sex the value for account.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.profession
     *
     * @return the value of account.profession
     *
     * @mbg.generated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.profession
     *
     * @param profession the value for account.profession
     *
     * @mbg.generated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.income
     *
     * @return the value of account.income
     *
     * @mbg.generated
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.income
     *
     * @param income the value for account.income
     *
     * @mbg.generated
     */
    public void setIncome(String income) {
        this.income = income == null ? null : income.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.province
     *
     * @return the value of account.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.province
     *
     * @param province the value for account.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.city
     *
     * @return the value of account.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.city
     *
     * @param city the value for account.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.county
     *
     * @return the value of account.county
     *
     * @mbg.generated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.county
     *
     * @param county the value for account.county
     *
     * @mbg.generated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.position
     *
     * @return the value of account.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.position
     *
     * @param position the value for account.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.teacherId
     *
     * @return the value of account.teacherId
     *
     * @mbg.generated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.teacherId
     *
     * @param teacherid the value for account.teacherId
     *
     * @mbg.generated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.teacheName
     *
     * @return the value of account.teacheName
     *
     * @mbg.generated
     */
    public String getTeachename() {
        return teachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.teacheName
     *
     * @param teachename the value for account.teacheName
     *
     * @mbg.generated
     */
    public void setTeachename(String teachename) {
        this.teachename = teachename == null ? null : teachename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.people
     *
     * @return the value of account.people
     *
     * @mbg.generated
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.people
     *
     * @param people the value for account.people
     *
     * @mbg.generated
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ident
     *
     * @return the value of account.ident
     *
     * @mbg.generated
     */
    public String getIdent() {
        return ident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ident
     *
     * @param ident the value for account.ident
     *
     * @mbg.generated
     */
    public void setIdent(String ident) {
        this.ident = ident == null ? null : ident.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.rhdate
     *
     * @return the value of account.rhdate
     *
     * @mbg.generated
     */
    public Date getRhdate() {
        return rhdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.rhdate
     *
     * @param rhdate the value for account.rhdate
     *
     * @mbg.generated
     */
    public void setRhdate(Date rhdate) {
        this.rhdate = rhdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.duration
     *
     * @return the value of account.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.duration
     *
     * @param duration the value for account.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ssqs
     *
     * @return the value of account.ssqs
     *
     * @mbg.generated
     */
    public String getSsqs() {
        return ssqs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ssqs
     *
     * @param ssqs the value for account.ssqs
     *
     * @mbg.generated
     */
    public void setSsqs(String ssqs) {
        this.ssqs = ssqs == null ? null : ssqs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.csdd
     *
     * @return the value of account.csdd
     *
     * @mbg.generated
     */
    public String getCsdd() {
        return csdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.csdd
     *
     * @param csdd the value for account.csdd
     *
     * @mbg.generated
     */
    public void setCsdd(String csdd) {
        this.csdd = csdd == null ? null : csdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.userType
     *
     * @return the value of account.userType
     *
     * @mbg.generated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.userType
     *
     * @param usertype the value for account.userType
     *
     * @mbg.generated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.praise
     *
     * @return the value of account.praise
     *
     * @mbg.generated
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.praise
     *
     * @param praise the value for account.praise
     *
     * @mbg.generated
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.follow
     *
     * @return the value of account.follow
     *
     * @mbg.generated
     */
    public Integer getFollow() {
        return follow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.follow
     *
     * @param follow the value for account.follow
     *
     * @mbg.generated
     */
    public void setFollow(Integer follow) {
        this.follow = follow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.publish
     *
     * @return the value of account.publish
     *
     * @mbg.generated
     */
    public Integer getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.publish
     *
     * @param publish the value for account.publish
     *
     * @mbg.generated
     */
    public void setPublish(Integer publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.wealth
     *
     * @return the value of account.wealth
     *
     * @mbg.generated
     */
    public Double getWealth() {
        return wealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.wealth
     *
     * @param wealth the value for account.wealth
     *
     * @mbg.generated
     */
    public void setWealth(Double wealth) {
        this.wealth = wealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.balance
     *
     * @return the value of account.balance
     *
     * @mbg.generated
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.balance
     *
     * @param balance the value for account.balance
     *
     * @mbg.generated
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.enabled
     *
     * @return the value of account.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.enabled
     *
     * @param enabled the value for account.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.introduce
     *
     * @return the value of account.introduce
     *
     * @mbg.generated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.introduce
     *
     * @param introduce the value for account.introduce
     *
     * @mbg.generated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", nickname=").append(nickname);
        sb.append(", username=").append(username);
        sb.append(", motto=").append(motto);
        sb.append(", birthday=").append(birthday);
        sb.append(", schooling=").append(schooling);
        sb.append(", sex=").append(sex);
        sb.append(", profession=").append(profession);
        sb.append(", income=").append(income);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", county=").append(county);
        sb.append(", position=").append(position);
        sb.append(", teacherid=").append(teacherid);
        sb.append(", teachename=").append(teachename);
        sb.append(", people=").append(people);
        sb.append(", ident=").append(ident);
        sb.append(", rhdate=").append(rhdate);
        sb.append(", duration=").append(duration);
        sb.append(", ssqs=").append(ssqs);
        sb.append(", csdd=").append(csdd);
        sb.append(", usertype=").append(usertype);
        sb.append(", praise=").append(praise);
        sb.append(", follow=").append(follow);
        sb.append(", publish=").append(publish);
        sb.append(", wealth=").append(wealth);
        sb.append(", balance=").append(balance);
        sb.append(", enabled=").append(enabled);
        sb.append(", introduce=").append(introduce);
        sb.append("]");
        return sb.toString();
    }
}