package com.data.pojo;

import java.io.Serializable;
import java.util.Date;

public class VoteSubject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.UpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.IsDelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.LoginLimited
     *
     * @mbg.generated
     */
    private Integer loginlimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.TimeLimited
     *
     * @mbg.generated
     */
    private Integer timelimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.VoteTotals
     *
     * @mbg.generated
     */
    private Integer votetotals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.UserId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.CreateBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.Id
     *
     * @return the value of vote_subject.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.Id
     *
     * @param id the value for vote_subject.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.Title
     *
     * @return the value of vote_subject.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.Title
     *
     * @param title the value for vote_subject.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.CreateTime
     *
     * @return the value of vote_subject.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.CreateTime
     *
     * @param createtime the value for vote_subject.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.UpdateTime
     *
     * @return the value of vote_subject.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.UpdateTime
     *
     * @param updatetime the value for vote_subject.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.IsDelete
     *
     * @return the value of vote_subject.IsDelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.IsDelete
     *
     * @param isdelete the value for vote_subject.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.type
     *
     * @return the value of vote_subject.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.type
     *
     * @param type the value for vote_subject.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.LoginLimited
     *
     * @return the value of vote_subject.LoginLimited
     *
     * @mbg.generated
     */
    public Integer getLoginlimited() {
        return loginlimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.LoginLimited
     *
     * @param loginlimited the value for vote_subject.LoginLimited
     *
     * @mbg.generated
     */
    public void setLoginlimited(Integer loginlimited) {
        this.loginlimited = loginlimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.endtime
     *
     * @return the value of vote_subject.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.endtime
     *
     * @param endtime the value for vote_subject.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.TimeLimited
     *
     * @return the value of vote_subject.TimeLimited
     *
     * @mbg.generated
     */
    public Integer getTimelimited() {
        return timelimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.TimeLimited
     *
     * @param timelimited the value for vote_subject.TimeLimited
     *
     * @mbg.generated
     */
    public void setTimelimited(Integer timelimited) {
        this.timelimited = timelimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.VoteTotals
     *
     * @return the value of vote_subject.VoteTotals
     *
     * @mbg.generated
     */
    public Integer getVotetotals() {
        return votetotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.VoteTotals
     *
     * @param votetotals the value for vote_subject.VoteTotals
     *
     * @mbg.generated
     */
    public void setVotetotals(Integer votetotals) {
        this.votetotals = votetotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.UserId
     *
     * @return the value of vote_subject.UserId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.UserId
     *
     * @param userid the value for vote_subject.UserId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.CreateBy
     *
     * @return the value of vote_subject.CreateBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.CreateBy
     *
     * @param createby the value for vote_subject.CreateBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", type=").append(type);
        sb.append(", loginlimited=").append(loginlimited);
        sb.append(", endtime=").append(endtime);
        sb.append(", timelimited=").append(timelimited);
        sb.append(", votetotals=").append(votetotals);
        sb.append(", userid=").append(userid);
        sb.append(", createby=").append(createby);
        sb.append("]");
        return sb.toString();
    }
}