package com.data.pojo;

import java.io.Serializable;
import java.util.Date;

public class VotePkSubject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.UpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.IsDelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.LoginLimited
     *
     * @mbg.generated
     */
    private Integer loginlimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.TimeLimited
     *
     * @mbg.generated
     */
    private Integer timelimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.ProPosition
     *
     * @mbg.generated
     */
    private String proposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.ProPositionImg
     *
     * @mbg.generated
     */
    private String propositionimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.ProVotes
     *
     * @mbg.generated
     */
    private Integer provotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.Opposition
     *
     * @mbg.generated
     */
    private String opposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.OppositionImg
     *
     * @mbg.generated
     */
    private String oppositionimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.OppVotes
     *
     * @mbg.generated
     */
    private Integer oppvotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.VoteTotals
     *
     * @mbg.generated
     */
    private Integer votetotals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.UserId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subject.CreateBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.Id
     *
     * @return the value of vote_pk_subject.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.Id
     *
     * @param id the value for vote_pk_subject.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.Title
     *
     * @return the value of vote_pk_subject.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.Title
     *
     * @param title the value for vote_pk_subject.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.CreateTime
     *
     * @return the value of vote_pk_subject.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.CreateTime
     *
     * @param createtime the value for vote_pk_subject.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.UpdateTime
     *
     * @return the value of vote_pk_subject.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.UpdateTime
     *
     * @param updatetime the value for vote_pk_subject.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.IsDelete
     *
     * @return the value of vote_pk_subject.IsDelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.IsDelete
     *
     * @param isdelete the value for vote_pk_subject.IsDelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.LoginLimited
     *
     * @return the value of vote_pk_subject.LoginLimited
     *
     * @mbg.generated
     */
    public Integer getLoginlimited() {
        return loginlimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.LoginLimited
     *
     * @param loginlimited the value for vote_pk_subject.LoginLimited
     *
     * @mbg.generated
     */
    public void setLoginlimited(Integer loginlimited) {
        this.loginlimited = loginlimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.endtime
     *
     * @return the value of vote_pk_subject.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.endtime
     *
     * @param endtime the value for vote_pk_subject.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.TimeLimited
     *
     * @return the value of vote_pk_subject.TimeLimited
     *
     * @mbg.generated
     */
    public Integer getTimelimited() {
        return timelimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.TimeLimited
     *
     * @param timelimited the value for vote_pk_subject.TimeLimited
     *
     * @mbg.generated
     */
    public void setTimelimited(Integer timelimited) {
        this.timelimited = timelimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.ProPosition
     *
     * @return the value of vote_pk_subject.ProPosition
     *
     * @mbg.generated
     */
    public String getProposition() {
        return proposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.ProPosition
     *
     * @param proposition the value for vote_pk_subject.ProPosition
     *
     * @mbg.generated
     */
    public void setProposition(String proposition) {
        this.proposition = proposition == null ? null : proposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.ProPositionImg
     *
     * @return the value of vote_pk_subject.ProPositionImg
     *
     * @mbg.generated
     */
    public String getPropositionimg() {
        return propositionimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.ProPositionImg
     *
     * @param propositionimg the value for vote_pk_subject.ProPositionImg
     *
     * @mbg.generated
     */
    public void setPropositionimg(String propositionimg) {
        this.propositionimg = propositionimg == null ? null : propositionimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.ProVotes
     *
     * @return the value of vote_pk_subject.ProVotes
     *
     * @mbg.generated
     */
    public Integer getProvotes() {
        return provotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.ProVotes
     *
     * @param provotes the value for vote_pk_subject.ProVotes
     *
     * @mbg.generated
     */
    public void setProvotes(Integer provotes) {
        this.provotes = provotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.Opposition
     *
     * @return the value of vote_pk_subject.Opposition
     *
     * @mbg.generated
     */
    public String getOpposition() {
        return opposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.Opposition
     *
     * @param opposition the value for vote_pk_subject.Opposition
     *
     * @mbg.generated
     */
    public void setOpposition(String opposition) {
        this.opposition = opposition == null ? null : opposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.OppositionImg
     *
     * @return the value of vote_pk_subject.OppositionImg
     *
     * @mbg.generated
     */
    public String getOppositionimg() {
        return oppositionimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.OppositionImg
     *
     * @param oppositionimg the value for vote_pk_subject.OppositionImg
     *
     * @mbg.generated
     */
    public void setOppositionimg(String oppositionimg) {
        this.oppositionimg = oppositionimg == null ? null : oppositionimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.OppVotes
     *
     * @return the value of vote_pk_subject.OppVotes
     *
     * @mbg.generated
     */
    public Integer getOppvotes() {
        return oppvotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.OppVotes
     *
     * @param oppvotes the value for vote_pk_subject.OppVotes
     *
     * @mbg.generated
     */
    public void setOppvotes(Integer oppvotes) {
        this.oppvotes = oppvotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.VoteTotals
     *
     * @return the value of vote_pk_subject.VoteTotals
     *
     * @mbg.generated
     */
    public Integer getVotetotals() {
        return votetotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.VoteTotals
     *
     * @param votetotals the value for vote_pk_subject.VoteTotals
     *
     * @mbg.generated
     */
    public void setVotetotals(Integer votetotals) {
        this.votetotals = votetotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.UserId
     *
     * @return the value of vote_pk_subject.UserId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.UserId
     *
     * @param userid the value for vote_pk_subject.UserId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subject.CreateBy
     *
     * @return the value of vote_pk_subject.CreateBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subject.CreateBy
     *
     * @param createby the value for vote_pk_subject.CreateBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", loginlimited=").append(loginlimited);
        sb.append(", endtime=").append(endtime);
        sb.append(", timelimited=").append(timelimited);
        sb.append(", proposition=").append(proposition);
        sb.append(", propositionimg=").append(propositionimg);
        sb.append(", provotes=").append(provotes);
        sb.append(", opposition=").append(opposition);
        sb.append(", oppositionimg=").append(oppositionimg);
        sb.append(", oppvotes=").append(oppvotes);
        sb.append(", votetotals=").append(votetotals);
        sb.append(", userid=").append(userid);
        sb.append(", createby=").append(createby);
        sb.append("]");
        return sb.toString();
    }
}