package com.data.pojo;

import java.io.Serializable;
import java.util.Date;

public class VoteSubjectanswer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.SubjectId
     *
     * @mbg.generated
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.SubjectOptionIds
     *
     * @mbg.generated
     */
    private String subjectoptionids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.AutohomeId
     *
     * @mbg.generated
     */
    private String autohomeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.NotLoginId
     *
     * @mbg.generated
     */
    private String notloginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.IP
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectanswer.AppId
     *
     * @mbg.generated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.Id
     *
     * @return the value of vote_subjectanswer.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.Id
     *
     * @param id the value for vote_subjectanswer.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.SubjectId
     *
     * @return the value of vote_subjectanswer.SubjectId
     *
     * @mbg.generated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.SubjectId
     *
     * @param subjectid the value for vote_subjectanswer.SubjectId
     *
     * @mbg.generated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.SubjectOptionIds
     *
     * @return the value of vote_subjectanswer.SubjectOptionIds
     *
     * @mbg.generated
     */
    public String getSubjectoptionids() {
        return subjectoptionids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.SubjectOptionIds
     *
     * @param subjectoptionids the value for vote_subjectanswer.SubjectOptionIds
     *
     * @mbg.generated
     */
    public void setSubjectoptionids(String subjectoptionids) {
        this.subjectoptionids = subjectoptionids == null ? null : subjectoptionids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.AutohomeId
     *
     * @return the value of vote_subjectanswer.AutohomeId
     *
     * @mbg.generated
     */
    public String getAutohomeid() {
        return autohomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.AutohomeId
     *
     * @param autohomeid the value for vote_subjectanswer.AutohomeId
     *
     * @mbg.generated
     */
    public void setAutohomeid(String autohomeid) {
        this.autohomeid = autohomeid == null ? null : autohomeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.NotLoginId
     *
     * @return the value of vote_subjectanswer.NotLoginId
     *
     * @mbg.generated
     */
    public String getNotloginid() {
        return notloginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.NotLoginId
     *
     * @param notloginid the value for vote_subjectanswer.NotLoginId
     *
     * @mbg.generated
     */
    public void setNotloginid(String notloginid) {
        this.notloginid = notloginid == null ? null : notloginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.IP
     *
     * @return the value of vote_subjectanswer.IP
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.IP
     *
     * @param ip the value for vote_subjectanswer.IP
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.CreateTime
     *
     * @return the value of vote_subjectanswer.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.CreateTime
     *
     * @param createtime the value for vote_subjectanswer.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectanswer.AppId
     *
     * @return the value of vote_subjectanswer.AppId
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectanswer.AppId
     *
     * @param appid the value for vote_subjectanswer.AppId
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subjectid=").append(subjectid);
        sb.append(", subjectoptionids=").append(subjectoptionids);
        sb.append(", autohomeid=").append(autohomeid);
        sb.append(", notloginid=").append(notloginid);
        sb.append(", ip=").append(ip);
        sb.append(", createtime=").append(createtime);
        sb.append(", appid=").append(appid);
        sb.append("]");
        return sb.toString();
    }
}