package com.data.pojo;

import java.util.ArrayList;
import java.util.List;

public class VoteSubjectoptionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public VoteSubjectoptionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubjectidIsNull() {
            addCriterion("SubjectId is null");
            return (Criteria) this;
        }

        public Criteria andSubjectidIsNotNull() {
            addCriterion("SubjectId is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectidEqualTo(Integer value) {
            addCriterion("SubjectId =", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidNotEqualTo(Integer value) {
            addCriterion("SubjectId <>", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidGreaterThan(Integer value) {
            addCriterion("SubjectId >", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SubjectId >=", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidLessThan(Integer value) {
            addCriterion("SubjectId <", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidLessThanOrEqualTo(Integer value) {
            addCriterion("SubjectId <=", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidIn(List<Integer> values) {
            addCriterion("SubjectId in", values, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidNotIn(List<Integer> values) {
            addCriterion("SubjectId not in", values, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidBetween(Integer value1, Integer value2) {
            addCriterion("SubjectId between", value1, value2, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidNotBetween(Integer value1, Integer value2) {
            addCriterion("SubjectId not between", value1, value2, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionIsNull() {
            addCriterion("SubjectOption is null");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionIsNotNull() {
            addCriterion("SubjectOption is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionEqualTo(String value) {
            addCriterion("SubjectOption =", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionNotEqualTo(String value) {
            addCriterion("SubjectOption <>", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionGreaterThan(String value) {
            addCriterion("SubjectOption >", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionGreaterThanOrEqualTo(String value) {
            addCriterion("SubjectOption >=", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionLessThan(String value) {
            addCriterion("SubjectOption <", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionLessThanOrEqualTo(String value) {
            addCriterion("SubjectOption <=", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionLike(String value) {
            addCriterion("SubjectOption like", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionNotLike(String value) {
            addCriterion("SubjectOption not like", value, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionIn(List<String> values) {
            addCriterion("SubjectOption in", values, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionNotIn(List<String> values) {
            addCriterion("SubjectOption not in", values, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionBetween(String value1, String value2) {
            addCriterion("SubjectOption between", value1, value2, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionNotBetween(String value1, String value2) {
            addCriterion("SubjectOption not between", value1, value2, "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgIsNull() {
            addCriterion("SubjectOptionImg is null");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgIsNotNull() {
            addCriterion("SubjectOptionImg is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgEqualTo(String value) {
            addCriterion("SubjectOptionImg =", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgNotEqualTo(String value) {
            addCriterion("SubjectOptionImg <>", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgGreaterThan(String value) {
            addCriterion("SubjectOptionImg >", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgGreaterThanOrEqualTo(String value) {
            addCriterion("SubjectOptionImg >=", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgLessThan(String value) {
            addCriterion("SubjectOptionImg <", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgLessThanOrEqualTo(String value) {
            addCriterion("SubjectOptionImg <=", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgLike(String value) {
            addCriterion("SubjectOptionImg like", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgNotLike(String value) {
            addCriterion("SubjectOptionImg not like", value, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgIn(List<String> values) {
            addCriterion("SubjectOptionImg in", values, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgNotIn(List<String> values) {
            addCriterion("SubjectOptionImg not in", values, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgBetween(String value1, String value2) {
            addCriterion("SubjectOptionImg between", value1, value2, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgNotBetween(String value1, String value2) {
            addCriterion("SubjectOptionImg not between", value1, value2, "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNull() {
            addCriterion("Remark1 is null");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNotNull() {
            addCriterion("Remark1 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark1EqualTo(String value) {
            addCriterion("Remark1 =", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotEqualTo(String value) {
            addCriterion("Remark1 <>", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThan(String value) {
            addCriterion("Remark1 >", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThanOrEqualTo(String value) {
            addCriterion("Remark1 >=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThan(String value) {
            addCriterion("Remark1 <", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThanOrEqualTo(String value) {
            addCriterion("Remark1 <=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Like(String value) {
            addCriterion("Remark1 like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotLike(String value) {
            addCriterion("Remark1 not like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1In(List<String> values) {
            addCriterion("Remark1 in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotIn(List<String> values) {
            addCriterion("Remark1 not in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Between(String value1, String value2) {
            addCriterion("Remark1 between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotBetween(String value1, String value2) {
            addCriterion("Remark1 not between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andOrdernumIsNull() {
            addCriterion("OrderNum is null");
            return (Criteria) this;
        }

        public Criteria andOrdernumIsNotNull() {
            addCriterion("OrderNum is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernumEqualTo(Integer value) {
            addCriterion("OrderNum =", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumNotEqualTo(Integer value) {
            addCriterion("OrderNum <>", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumGreaterThan(Integer value) {
            addCriterion("OrderNum >", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumGreaterThanOrEqualTo(Integer value) {
            addCriterion("OrderNum >=", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumLessThan(Integer value) {
            addCriterion("OrderNum <", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumLessThanOrEqualTo(Integer value) {
            addCriterion("OrderNum <=", value, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumIn(List<Integer> values) {
            addCriterion("OrderNum in", values, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumNotIn(List<Integer> values) {
            addCriterion("OrderNum not in", values, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumBetween(Integer value1, Integer value2) {
            addCriterion("OrderNum between", value1, value2, "ordernum");
            return (Criteria) this;
        }

        public Criteria andOrdernumNotBetween(Integer value1, Integer value2) {
            addCriterion("OrderNum not between", value1, value2, "ordernum");
            return (Criteria) this;
        }

        public Criteria andVotesIsNull() {
            addCriterion("Votes is null");
            return (Criteria) this;
        }

        public Criteria andVotesIsNotNull() {
            addCriterion("Votes is not null");
            return (Criteria) this;
        }

        public Criteria andVotesEqualTo(Integer value) {
            addCriterion("Votes =", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesNotEqualTo(Integer value) {
            addCriterion("Votes <>", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesGreaterThan(Integer value) {
            addCriterion("Votes >", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesGreaterThanOrEqualTo(Integer value) {
            addCriterion("Votes >=", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesLessThan(Integer value) {
            addCriterion("Votes <", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesLessThanOrEqualTo(Integer value) {
            addCriterion("Votes <=", value, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesIn(List<Integer> values) {
            addCriterion("Votes in", values, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesNotIn(List<Integer> values) {
            addCriterion("Votes not in", values, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesBetween(Integer value1, Integer value2) {
            addCriterion("Votes between", value1, value2, "votes");
            return (Criteria) this;
        }

        public Criteria andVotesNotBetween(Integer value1, Integer value2) {
            addCriterion("Votes not between", value1, value2, "votes");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("Rate is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("Rate is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(Float value) {
            addCriterion("Rate =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(Float value) {
            addCriterion("Rate <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(Float value) {
            addCriterion("Rate >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(Float value) {
            addCriterion("Rate >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(Float value) {
            addCriterion("Rate <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(Float value) {
            addCriterion("Rate <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<Float> values) {
            addCriterion("Rate in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<Float> values) {
            addCriterion("Rate not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(Float value1, Float value2) {
            addCriterion("Rate between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(Float value1, Float value2) {
            addCriterion("Rate not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andVotetotalsIsNull() {
            addCriterion("VoteTotals is null");
            return (Criteria) this;
        }

        public Criteria andVotetotalsIsNotNull() {
            addCriterion("VoteTotals is not null");
            return (Criteria) this;
        }

        public Criteria andVotetotalsEqualTo(Integer value) {
            addCriterion("VoteTotals =", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsNotEqualTo(Integer value) {
            addCriterion("VoteTotals <>", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsGreaterThan(Integer value) {
            addCriterion("VoteTotals >", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsGreaterThanOrEqualTo(Integer value) {
            addCriterion("VoteTotals >=", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsLessThan(Integer value) {
            addCriterion("VoteTotals <", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsLessThanOrEqualTo(Integer value) {
            addCriterion("VoteTotals <=", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsIn(List<Integer> values) {
            addCriterion("VoteTotals in", values, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsNotIn(List<Integer> values) {
            addCriterion("VoteTotals not in", values, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsBetween(Integer value1, Integer value2) {
            addCriterion("VoteTotals between", value1, value2, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsNotBetween(Integer value1, Integer value2) {
            addCriterion("VoteTotals not between", value1, value2, "votetotals");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionLikeInsensitive(String value) {
            addCriterion("upper(SubjectOption) like", value.toUpperCase(), "subjectoption");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionimgLikeInsensitive(String value) {
            addCriterion("upper(SubjectOptionImg) like", value.toUpperCase(), "subjectoptionimg");
            return (Criteria) this;
        }

        public Criteria andRemark1LikeInsensitive(String value) {
            addCriterion("upper(Remark1) like", value.toUpperCase(), "remark1");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_subjectoption
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}