package com.data.pojo;

import java.io.Serializable;

public class VoteSubjectoption implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.SubjectId
     *
     * @mbg.generated
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.SubjectOption
     *
     * @mbg.generated
     */
    private String subjectoption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.SubjectOptionImg
     *
     * @mbg.generated
     */
    private String subjectoptionimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.Remark1
     *
     * @mbg.generated
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.OrderNum
     *
     * @mbg.generated
     */
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.Votes
     *
     * @mbg.generated
     */
    private Integer votes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.Rate
     *
     * @mbg.generated
     */
    private Float rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.VoteTotals
     *
     * @mbg.generated
     */
    private Integer votetotals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subjectoption.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.Id
     *
     * @return the value of vote_subjectoption.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.Id
     *
     * @param id the value for vote_subjectoption.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.SubjectId
     *
     * @return the value of vote_subjectoption.SubjectId
     *
     * @mbg.generated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.SubjectId
     *
     * @param subjectid the value for vote_subjectoption.SubjectId
     *
     * @mbg.generated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.SubjectOption
     *
     * @return the value of vote_subjectoption.SubjectOption
     *
     * @mbg.generated
     */
    public String getSubjectoption() {
        return subjectoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.SubjectOption
     *
     * @param subjectoption the value for vote_subjectoption.SubjectOption
     *
     * @mbg.generated
     */
    public void setSubjectoption(String subjectoption) {
        this.subjectoption = subjectoption == null ? null : subjectoption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.SubjectOptionImg
     *
     * @return the value of vote_subjectoption.SubjectOptionImg
     *
     * @mbg.generated
     */
    public String getSubjectoptionimg() {
        return subjectoptionimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.SubjectOptionImg
     *
     * @param subjectoptionimg the value for vote_subjectoption.SubjectOptionImg
     *
     * @mbg.generated
     */
    public void setSubjectoptionimg(String subjectoptionimg) {
        this.subjectoptionimg = subjectoptionimg == null ? null : subjectoptionimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.Remark1
     *
     * @return the value of vote_subjectoption.Remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.Remark1
     *
     * @param remark1 the value for vote_subjectoption.Remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.OrderNum
     *
     * @return the value of vote_subjectoption.OrderNum
     *
     * @mbg.generated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.OrderNum
     *
     * @param ordernum the value for vote_subjectoption.OrderNum
     *
     * @mbg.generated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.Votes
     *
     * @return the value of vote_subjectoption.Votes
     *
     * @mbg.generated
     */
    public Integer getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.Votes
     *
     * @param votes the value for vote_subjectoption.Votes
     *
     * @mbg.generated
     */
    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.Rate
     *
     * @return the value of vote_subjectoption.Rate
     *
     * @mbg.generated
     */
    public Float getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.Rate
     *
     * @param rate the value for vote_subjectoption.Rate
     *
     * @mbg.generated
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.VoteTotals
     *
     * @return the value of vote_subjectoption.VoteTotals
     *
     * @mbg.generated
     */
    public Integer getVotetotals() {
        return votetotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.VoteTotals
     *
     * @param votetotals the value for vote_subjectoption.VoteTotals
     *
     * @mbg.generated
     */
    public void setVotetotals(Integer votetotals) {
        this.votetotals = votetotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subjectoption.score
     *
     * @return the value of vote_subjectoption.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subjectoption.score
     *
     * @param score the value for vote_subjectoption.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectoption
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subjectid=").append(subjectid);
        sb.append(", subjectoption=").append(subjectoption);
        sb.append(", subjectoptionimg=").append(subjectoptionimg);
        sb.append(", remark1=").append(remark1);
        sb.append(", ordernum=").append(ordernum);
        sb.append(", votes=").append(votes);
        sb.append(", rate=").append(rate);
        sb.append(", votetotals=").append(votetotals);
        sb.append(", score=").append(score);
        sb.append("]");
        return sb.toString();
    }
}