package com.data.pojo;

import java.io.Serializable;

public class VotePkSubjectoption implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.SubjectId
     *
     * @mbg.generated
     */
    private Integer subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.SubjectSide
     *
     * @mbg.generated
     */
    private Integer subjectside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.SubjectOption
     *
     * @mbg.generated
     */
    private String subjectoption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.SubjectOptionImg
     *
     * @mbg.generated
     */
    private String subjectoptionimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.Remark1
     *
     * @mbg.generated
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_pk_subjectoption.OrderNum
     *
     * @mbg.generated
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.Id
     *
     * @return the value of vote_pk_subjectoption.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.Id
     *
     * @param id the value for vote_pk_subjectoption.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.SubjectId
     *
     * @return the value of vote_pk_subjectoption.SubjectId
     *
     * @mbg.generated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.SubjectId
     *
     * @param subjectid the value for vote_pk_subjectoption.SubjectId
     *
     * @mbg.generated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.SubjectSide
     *
     * @return the value of vote_pk_subjectoption.SubjectSide
     *
     * @mbg.generated
     */
    public Integer getSubjectside() {
        return subjectside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.SubjectSide
     *
     * @param subjectside the value for vote_pk_subjectoption.SubjectSide
     *
     * @mbg.generated
     */
    public void setSubjectside(Integer subjectside) {
        this.subjectside = subjectside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.SubjectOption
     *
     * @return the value of vote_pk_subjectoption.SubjectOption
     *
     * @mbg.generated
     */
    public String getSubjectoption() {
        return subjectoption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.SubjectOption
     *
     * @param subjectoption the value for vote_pk_subjectoption.SubjectOption
     *
     * @mbg.generated
     */
    public void setSubjectoption(String subjectoption) {
        this.subjectoption = subjectoption == null ? null : subjectoption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.SubjectOptionImg
     *
     * @return the value of vote_pk_subjectoption.SubjectOptionImg
     *
     * @mbg.generated
     */
    public String getSubjectoptionimg() {
        return subjectoptionimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.SubjectOptionImg
     *
     * @param subjectoptionimg the value for vote_pk_subjectoption.SubjectOptionImg
     *
     * @mbg.generated
     */
    public void setSubjectoptionimg(String subjectoptionimg) {
        this.subjectoptionimg = subjectoptionimg == null ? null : subjectoptionimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.Remark1
     *
     * @return the value of vote_pk_subjectoption.Remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.Remark1
     *
     * @param remark1 the value for vote_pk_subjectoption.Remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_pk_subjectoption.OrderNum
     *
     * @return the value of vote_pk_subjectoption.OrderNum
     *
     * @mbg.generated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_pk_subjectoption.OrderNum
     *
     * @param ordernum the value for vote_pk_subjectoption.OrderNum
     *
     * @mbg.generated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subjectoption
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", subjectid=").append(subjectid);
        sb.append(", subjectside=").append(subjectside);
        sb.append(", subjectoption=").append(subjectoption);
        sb.append(", subjectoptionimg=").append(subjectoptionimg);
        sb.append(", remark1=").append(remark1);
        sb.append(", ordernum=").append(ordernum);
        sb.append("]");
        return sb.toString();
    }
}