package com.data.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VoteSubjectanswerCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public VoteSubjectanswerCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubjectidIsNull() {
            addCriterion("SubjectId is null");
            return (Criteria) this;
        }

        public Criteria andSubjectidIsNotNull() {
            addCriterion("SubjectId is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectidEqualTo(Integer value) {
            addCriterion("SubjectId =", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidNotEqualTo(Integer value) {
            addCriterion("SubjectId <>", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidGreaterThan(Integer value) {
            addCriterion("SubjectId >", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SubjectId >=", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidLessThan(Integer value) {
            addCriterion("SubjectId <", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidLessThanOrEqualTo(Integer value) {
            addCriterion("SubjectId <=", value, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidIn(List<Integer> values) {
            addCriterion("SubjectId in", values, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidNotIn(List<Integer> values) {
            addCriterion("SubjectId not in", values, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidBetween(Integer value1, Integer value2) {
            addCriterion("SubjectId between", value1, value2, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectidNotBetween(Integer value1, Integer value2) {
            addCriterion("SubjectId not between", value1, value2, "subjectid");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsIsNull() {
            addCriterion("SubjectOptionIds is null");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsIsNotNull() {
            addCriterion("SubjectOptionIds is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsEqualTo(String value) {
            addCriterion("SubjectOptionIds =", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsNotEqualTo(String value) {
            addCriterion("SubjectOptionIds <>", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsGreaterThan(String value) {
            addCriterion("SubjectOptionIds >", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsGreaterThanOrEqualTo(String value) {
            addCriterion("SubjectOptionIds >=", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsLessThan(String value) {
            addCriterion("SubjectOptionIds <", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsLessThanOrEqualTo(String value) {
            addCriterion("SubjectOptionIds <=", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsLike(String value) {
            addCriterion("SubjectOptionIds like", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsNotLike(String value) {
            addCriterion("SubjectOptionIds not like", value, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsIn(List<String> values) {
            addCriterion("SubjectOptionIds in", values, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsNotIn(List<String> values) {
            addCriterion("SubjectOptionIds not in", values, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsBetween(String value1, String value2) {
            addCriterion("SubjectOptionIds between", value1, value2, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsNotBetween(String value1, String value2) {
            addCriterion("SubjectOptionIds not between", value1, value2, "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andAutohomeidIsNull() {
            addCriterion("AutohomeId is null");
            return (Criteria) this;
        }

        public Criteria andAutohomeidIsNotNull() {
            addCriterion("AutohomeId is not null");
            return (Criteria) this;
        }

        public Criteria andAutohomeidEqualTo(String value) {
            addCriterion("AutohomeId =", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidNotEqualTo(String value) {
            addCriterion("AutohomeId <>", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidGreaterThan(String value) {
            addCriterion("AutohomeId >", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidGreaterThanOrEqualTo(String value) {
            addCriterion("AutohomeId >=", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidLessThan(String value) {
            addCriterion("AutohomeId <", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidLessThanOrEqualTo(String value) {
            addCriterion("AutohomeId <=", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidLike(String value) {
            addCriterion("AutohomeId like", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidNotLike(String value) {
            addCriterion("AutohomeId not like", value, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidIn(List<String> values) {
            addCriterion("AutohomeId in", values, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidNotIn(List<String> values) {
            addCriterion("AutohomeId not in", values, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidBetween(String value1, String value2) {
            addCriterion("AutohomeId between", value1, value2, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andAutohomeidNotBetween(String value1, String value2) {
            addCriterion("AutohomeId not between", value1, value2, "autohomeid");
            return (Criteria) this;
        }

        public Criteria andNotloginidIsNull() {
            addCriterion("NotLoginId is null");
            return (Criteria) this;
        }

        public Criteria andNotloginidIsNotNull() {
            addCriterion("NotLoginId is not null");
            return (Criteria) this;
        }

        public Criteria andNotloginidEqualTo(String value) {
            addCriterion("NotLoginId =", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidNotEqualTo(String value) {
            addCriterion("NotLoginId <>", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidGreaterThan(String value) {
            addCriterion("NotLoginId >", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidGreaterThanOrEqualTo(String value) {
            addCriterion("NotLoginId >=", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidLessThan(String value) {
            addCriterion("NotLoginId <", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidLessThanOrEqualTo(String value) {
            addCriterion("NotLoginId <=", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidLike(String value) {
            addCriterion("NotLoginId like", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidNotLike(String value) {
            addCriterion("NotLoginId not like", value, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidIn(List<String> values) {
            addCriterion("NotLoginId in", values, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidNotIn(List<String> values) {
            addCriterion("NotLoginId not in", values, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidBetween(String value1, String value2) {
            addCriterion("NotLoginId between", value1, value2, "notloginid");
            return (Criteria) this;
        }

        public Criteria andNotloginidNotBetween(String value1, String value2) {
            addCriterion("NotLoginId not between", value1, value2, "notloginid");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("AppId is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("AppId is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("AppId =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("AppId <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("AppId >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("AppId >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("AppId <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("AppId <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("AppId like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("AppId not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("AppId in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("AppId not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("AppId between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("AppId not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andSubjectoptionidsLikeInsensitive(String value) {
            addCriterion("upper(SubjectOptionIds) like", value.toUpperCase(), "subjectoptionids");
            return (Criteria) this;
        }

        public Criteria andAutohomeidLikeInsensitive(String value) {
            addCriterion("upper(AutohomeId) like", value.toUpperCase(), "autohomeid");
            return (Criteria) this;
        }

        public Criteria andNotloginidLikeInsensitive(String value) {
            addCriterion("upper(NotLoginId) like", value.toUpperCase(), "notloginid");
            return (Criteria) this;
        }

        public Criteria andIpLikeInsensitive(String value) {
            addCriterion("upper(IP) like", value.toUpperCase(), "ip");
            return (Criteria) this;
        }

        public Criteria andAppidLikeInsensitive(String value) {
            addCriterion("upper(AppId) like", value.toUpperCase(), "appid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_subjectanswer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}