package com.data.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VotePkSubjectCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public VotePkSubjectCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UpdateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UpdateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("IsDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("IsDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("IsDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("IsDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("IsDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("IsDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("IsDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("IsDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("IsDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("IsDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("IsDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("IsDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedIsNull() {
            addCriterion("LoginLimited is null");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedIsNotNull() {
            addCriterion("LoginLimited is not null");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedEqualTo(Integer value) {
            addCriterion("LoginLimited =", value, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedNotEqualTo(Integer value) {
            addCriterion("LoginLimited <>", value, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedGreaterThan(Integer value) {
            addCriterion("LoginLimited >", value, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedGreaterThanOrEqualTo(Integer value) {
            addCriterion("LoginLimited >=", value, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedLessThan(Integer value) {
            addCriterion("LoginLimited <", value, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedLessThanOrEqualTo(Integer value) {
            addCriterion("LoginLimited <=", value, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedIn(List<Integer> values) {
            addCriterion("LoginLimited in", values, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedNotIn(List<Integer> values) {
            addCriterion("LoginLimited not in", values, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedBetween(Integer value1, Integer value2) {
            addCriterion("LoginLimited between", value1, value2, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andLoginlimitedNotBetween(Integer value1, Integer value2) {
            addCriterion("LoginLimited not between", value1, value2, "loginlimited");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andTimelimitedIsNull() {
            addCriterion("TimeLimited is null");
            return (Criteria) this;
        }

        public Criteria andTimelimitedIsNotNull() {
            addCriterion("TimeLimited is not null");
            return (Criteria) this;
        }

        public Criteria andTimelimitedEqualTo(Integer value) {
            addCriterion("TimeLimited =", value, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedNotEqualTo(Integer value) {
            addCriterion("TimeLimited <>", value, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedGreaterThan(Integer value) {
            addCriterion("TimeLimited >", value, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedGreaterThanOrEqualTo(Integer value) {
            addCriterion("TimeLimited >=", value, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedLessThan(Integer value) {
            addCriterion("TimeLimited <", value, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedLessThanOrEqualTo(Integer value) {
            addCriterion("TimeLimited <=", value, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedIn(List<Integer> values) {
            addCriterion("TimeLimited in", values, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedNotIn(List<Integer> values) {
            addCriterion("TimeLimited not in", values, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedBetween(Integer value1, Integer value2) {
            addCriterion("TimeLimited between", value1, value2, "timelimited");
            return (Criteria) this;
        }

        public Criteria andTimelimitedNotBetween(Integer value1, Integer value2) {
            addCriterion("TimeLimited not between", value1, value2, "timelimited");
            return (Criteria) this;
        }

        public Criteria andPropositionIsNull() {
            addCriterion("ProPosition is null");
            return (Criteria) this;
        }

        public Criteria andPropositionIsNotNull() {
            addCriterion("ProPosition is not null");
            return (Criteria) this;
        }

        public Criteria andPropositionEqualTo(String value) {
            addCriterion("ProPosition =", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionNotEqualTo(String value) {
            addCriterion("ProPosition <>", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionGreaterThan(String value) {
            addCriterion("ProPosition >", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionGreaterThanOrEqualTo(String value) {
            addCriterion("ProPosition >=", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionLessThan(String value) {
            addCriterion("ProPosition <", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionLessThanOrEqualTo(String value) {
            addCriterion("ProPosition <=", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionLike(String value) {
            addCriterion("ProPosition like", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionNotLike(String value) {
            addCriterion("ProPosition not like", value, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionIn(List<String> values) {
            addCriterion("ProPosition in", values, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionNotIn(List<String> values) {
            addCriterion("ProPosition not in", values, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionBetween(String value1, String value2) {
            addCriterion("ProPosition between", value1, value2, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionNotBetween(String value1, String value2) {
            addCriterion("ProPosition not between", value1, value2, "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionimgIsNull() {
            addCriterion("ProPositionImg is null");
            return (Criteria) this;
        }

        public Criteria andPropositionimgIsNotNull() {
            addCriterion("ProPositionImg is not null");
            return (Criteria) this;
        }

        public Criteria andPropositionimgEqualTo(String value) {
            addCriterion("ProPositionImg =", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgNotEqualTo(String value) {
            addCriterion("ProPositionImg <>", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgGreaterThan(String value) {
            addCriterion("ProPositionImg >", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgGreaterThanOrEqualTo(String value) {
            addCriterion("ProPositionImg >=", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgLessThan(String value) {
            addCriterion("ProPositionImg <", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgLessThanOrEqualTo(String value) {
            addCriterion("ProPositionImg <=", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgLike(String value) {
            addCriterion("ProPositionImg like", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgNotLike(String value) {
            addCriterion("ProPositionImg not like", value, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgIn(List<String> values) {
            addCriterion("ProPositionImg in", values, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgNotIn(List<String> values) {
            addCriterion("ProPositionImg not in", values, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgBetween(String value1, String value2) {
            addCriterion("ProPositionImg between", value1, value2, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andPropositionimgNotBetween(String value1, String value2) {
            addCriterion("ProPositionImg not between", value1, value2, "propositionimg");
            return (Criteria) this;
        }

        public Criteria andProvotesIsNull() {
            addCriterion("ProVotes is null");
            return (Criteria) this;
        }

        public Criteria andProvotesIsNotNull() {
            addCriterion("ProVotes is not null");
            return (Criteria) this;
        }

        public Criteria andProvotesEqualTo(Integer value) {
            addCriterion("ProVotes =", value, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesNotEqualTo(Integer value) {
            addCriterion("ProVotes <>", value, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesGreaterThan(Integer value) {
            addCriterion("ProVotes >", value, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesGreaterThanOrEqualTo(Integer value) {
            addCriterion("ProVotes >=", value, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesLessThan(Integer value) {
            addCriterion("ProVotes <", value, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesLessThanOrEqualTo(Integer value) {
            addCriterion("ProVotes <=", value, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesIn(List<Integer> values) {
            addCriterion("ProVotes in", values, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesNotIn(List<Integer> values) {
            addCriterion("ProVotes not in", values, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesBetween(Integer value1, Integer value2) {
            addCriterion("ProVotes between", value1, value2, "provotes");
            return (Criteria) this;
        }

        public Criteria andProvotesNotBetween(Integer value1, Integer value2) {
            addCriterion("ProVotes not between", value1, value2, "provotes");
            return (Criteria) this;
        }

        public Criteria andOppositionIsNull() {
            addCriterion("Opposition is null");
            return (Criteria) this;
        }

        public Criteria andOppositionIsNotNull() {
            addCriterion("Opposition is not null");
            return (Criteria) this;
        }

        public Criteria andOppositionEqualTo(String value) {
            addCriterion("Opposition =", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionNotEqualTo(String value) {
            addCriterion("Opposition <>", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionGreaterThan(String value) {
            addCriterion("Opposition >", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionGreaterThanOrEqualTo(String value) {
            addCriterion("Opposition >=", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionLessThan(String value) {
            addCriterion("Opposition <", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionLessThanOrEqualTo(String value) {
            addCriterion("Opposition <=", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionLike(String value) {
            addCriterion("Opposition like", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionNotLike(String value) {
            addCriterion("Opposition not like", value, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionIn(List<String> values) {
            addCriterion("Opposition in", values, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionNotIn(List<String> values) {
            addCriterion("Opposition not in", values, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionBetween(String value1, String value2) {
            addCriterion("Opposition between", value1, value2, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionNotBetween(String value1, String value2) {
            addCriterion("Opposition not between", value1, value2, "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionimgIsNull() {
            addCriterion("OppositionImg is null");
            return (Criteria) this;
        }

        public Criteria andOppositionimgIsNotNull() {
            addCriterion("OppositionImg is not null");
            return (Criteria) this;
        }

        public Criteria andOppositionimgEqualTo(String value) {
            addCriterion("OppositionImg =", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgNotEqualTo(String value) {
            addCriterion("OppositionImg <>", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgGreaterThan(String value) {
            addCriterion("OppositionImg >", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgGreaterThanOrEqualTo(String value) {
            addCriterion("OppositionImg >=", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgLessThan(String value) {
            addCriterion("OppositionImg <", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgLessThanOrEqualTo(String value) {
            addCriterion("OppositionImg <=", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgLike(String value) {
            addCriterion("OppositionImg like", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgNotLike(String value) {
            addCriterion("OppositionImg not like", value, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgIn(List<String> values) {
            addCriterion("OppositionImg in", values, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgNotIn(List<String> values) {
            addCriterion("OppositionImg not in", values, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgBetween(String value1, String value2) {
            addCriterion("OppositionImg between", value1, value2, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionimgNotBetween(String value1, String value2) {
            addCriterion("OppositionImg not between", value1, value2, "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andOppvotesIsNull() {
            addCriterion("OppVotes is null");
            return (Criteria) this;
        }

        public Criteria andOppvotesIsNotNull() {
            addCriterion("OppVotes is not null");
            return (Criteria) this;
        }

        public Criteria andOppvotesEqualTo(Integer value) {
            addCriterion("OppVotes =", value, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesNotEqualTo(Integer value) {
            addCriterion("OppVotes <>", value, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesGreaterThan(Integer value) {
            addCriterion("OppVotes >", value, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesGreaterThanOrEqualTo(Integer value) {
            addCriterion("OppVotes >=", value, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesLessThan(Integer value) {
            addCriterion("OppVotes <", value, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesLessThanOrEqualTo(Integer value) {
            addCriterion("OppVotes <=", value, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesIn(List<Integer> values) {
            addCriterion("OppVotes in", values, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesNotIn(List<Integer> values) {
            addCriterion("OppVotes not in", values, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesBetween(Integer value1, Integer value2) {
            addCriterion("OppVotes between", value1, value2, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andOppvotesNotBetween(Integer value1, Integer value2) {
            addCriterion("OppVotes not between", value1, value2, "oppvotes");
            return (Criteria) this;
        }

        public Criteria andVotetotalsIsNull() {
            addCriterion("VoteTotals is null");
            return (Criteria) this;
        }

        public Criteria andVotetotalsIsNotNull() {
            addCriterion("VoteTotals is not null");
            return (Criteria) this;
        }

        public Criteria andVotetotalsEqualTo(Integer value) {
            addCriterion("VoteTotals =", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsNotEqualTo(Integer value) {
            addCriterion("VoteTotals <>", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsGreaterThan(Integer value) {
            addCriterion("VoteTotals >", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsGreaterThanOrEqualTo(Integer value) {
            addCriterion("VoteTotals >=", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsLessThan(Integer value) {
            addCriterion("VoteTotals <", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsLessThanOrEqualTo(Integer value) {
            addCriterion("VoteTotals <=", value, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsIn(List<Integer> values) {
            addCriterion("VoteTotals in", values, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsNotIn(List<Integer> values) {
            addCriterion("VoteTotals not in", values, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsBetween(Integer value1, Integer value2) {
            addCriterion("VoteTotals between", value1, value2, "votetotals");
            return (Criteria) this;
        }

        public Criteria andVotetotalsNotBetween(Integer value1, Integer value2) {
            addCriterion("VoteTotals not between", value1, value2, "votetotals");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("UserId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("UserId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("UserId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("UserId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("UserId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("UserId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("UserId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("UserId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("UserId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("UserId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("UserId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("UserId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CreateBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CreateBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("CreateBy =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("CreateBy <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("CreateBy >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("CreateBy >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("CreateBy <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("CreateBy <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("CreateBy like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("CreateBy not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("CreateBy in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("CreateBy not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("CreateBy between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("CreateBy not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andTitleLikeInsensitive(String value) {
            addCriterion("upper(Title) like", value.toUpperCase(), "title");
            return (Criteria) this;
        }

        public Criteria andPropositionLikeInsensitive(String value) {
            addCriterion("upper(ProPosition) like", value.toUpperCase(), "proposition");
            return (Criteria) this;
        }

        public Criteria andPropositionimgLikeInsensitive(String value) {
            addCriterion("upper(ProPositionImg) like", value.toUpperCase(), "propositionimg");
            return (Criteria) this;
        }

        public Criteria andOppositionLikeInsensitive(String value) {
            addCriterion("upper(Opposition) like", value.toUpperCase(), "opposition");
            return (Criteria) this;
        }

        public Criteria andOppositionimgLikeInsensitive(String value) {
            addCriterion("upper(OppositionImg) like", value.toUpperCase(), "oppositionimg");
            return (Criteria) this;
        }

        public Criteria andCreatebyLikeInsensitive(String value) {
            addCriterion("upper(CreateBy) like", value.toUpperCase(), "createby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_pk_subject
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote_pk_subject
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}