package com.data.pojo;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.Id
     *
     * @mbg.generated Tue Feb 21 14:45:50 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.Name
     *
     * @mbg.generated Tue Feb 21 14:45:50 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.Id
     *
     * @return the value of category.Id
     *
     * @mbg.generated Tue Feb 21 14:45:50 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.Id
     *
     * @param id the value for category.Id
     *
     * @mbg.generated Tue Feb 21 14:45:50 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.Name
     *
     * @return the value of category.Name
     *
     * @mbg.generated Tue Feb 21 14:45:50 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.Name
     *
     * @param name the value for category.Name
     *
     * @mbg.generated Tue Feb 21 14:45:50 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}