package com.data.pojo;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Id
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.categoryId
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Name
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Id
     *
     * @return the value of product.Id
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Id
     *
     * @param id the value for product.Id
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.categoryId
     *
     * @return the value of product.categoryId
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.categoryId
     *
     * @param categoryid the value for product.categoryId
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Name
     *
     * @return the value of product.Name
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Name
     *
     * @param name the value for product.Name
     *
     * @mbg.generated Fri Feb 24 14:11:12 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}